### ISSUE TITLE
Trouble adding colorbar with matplotlib 3.3.3

### ISSUE THREAD

**Issue by jkanner** [gwpy/gwpy#1280]
I'm having trouble adding a colorbar to Q-transform plots with the command:

`ax.colorbar()`

As best I can tell, this works with matplotlib==3.3.0, but throws errors with matplotlib==3.3.3.

With matplotlib 3.3.3, I get the error:
AttributeError: 'XAxis' object has no attribute '_gridOnMinor'

and gets traced all the way to here:

File "/Users/jkanner/miniconda2/envs/stenvtest/lib/python3.7/site-packages/gwpy/plot/axes.py", line 89, in wrapped_func
` grid = (self.xaxis._gridOnMinor, self.xaxis._gridOnMajor,`

**Comment by duncanmmacleod** [comment]
This was fixed in #1278, we just need to cut a new release to get this fix into the wild.

**Comment by jkanner** [comment]
Great!  Thank you!  -jonah

On Nov 24, 2020, at 9:23 AM, Duncan Macleod <notifications@github.com<mailto:notifications@github.com>> wrote:



This was fixed in #1278<https://github.com/gwpy/gwpy/pull/1278>, we just need to cut a new release to get this fix into the wild.
